### ISSUE TITLE
Error with VA4220WF?

### ISSUE THREAD

**Issue by b0ne** [claudegel/sinope-130#139] opened 2023-01-24 15:41 UTC
HomeAssistant 2023.1.7, Sinope-130 v2.0.0

Error in log:
neviweb130: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 729, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/sensor.py", line 256, in update
    device_data[ATTR_WATER_LEAK_STATUS] == STATE_WATER_LEAK else "ok"
KeyError: 'waterLeakStatus'

**Comment by claudegel** [comment] 2023-01-25 01:42
Hi, the problem is not with your valve but with your leak sensor.
How they are connected ? directly to your valve or via the GT130
I'll need more log. can you provide your HA log line for your valve and your leak sensor
The line are the one that contain:
[custom_components.neviweb130.switch] Setting up neviweb130 switch «your valve»...
[custom_components.neviweb130.switch] Updating neviweb130 switch «your valve»...
[custom_components.neviweb130.sensor] Setting up neviweb130 sensor «your leak sensor»...
[custom_components.neviweb130.sensor] Updating neviweb130 sensor «your leak sensor»...
It look like the attribute name, waterLeakStatus, for leak status is different for your leak sensor. 
We need to find out how Neviweb call the attribute name for your leak sensor

**Comment by claudegel** [comment] 2023-01-27 01:08
Can you tell me if your leak sensor is connected directly to your valve or to the GT130

**Comment by b0ne** [comment] 2023-01-30 16:07
Sorry about the delay

The leaks sensor are connected to GT130 directly. I'm looking at the log and I don't see the line that you mention. Where do I have to look to find it?

Tks!

**Comment by b0ne** [comment] 2023-01-30 16:29
Ok,

I'm not sure if you need to fix it or not. The neviweb130 sensor WL4200S was actually offline (dead battery). I remove it from nevieweb for the moment (I will reset it later). And the log is clean at the moment (restarted home assistant). 

Tks!

**Comment by claudegel** [comment] 2023-02-07 01:18
Let me know if the problem is fixed. I'm closing this but feel free to reopen if it is not fixed

**Closed by claudegel** 2023-02-07 01:18 UTC
