### ISSUE TITLE
Neviweb130 Notifications

### ISSUE THREAD

**Issue by tessierp** [claudegel/sinope-130#262] opened 2024-09-10 22:21 UTC
Hi,

I was wondering if there was a way to limit the number of notifications for Neviweb130. I get about 10+ of these per day. Sometimes the Sinope Thermostat will quickly disconnect and reconnect and these notifications are thrown, it would be interesting to have a feature to limit the number of a same notification per day if possible.

![image](https://github.com/user-attachments/assets/6a8ab230-4418-407e-8bcc-90921d53253a)

**Comment by claudegel** [comment] 2024-09-12 01:32
the notifications are sent when a device become unavailable in Neviweb. This is more frequent for the wifi device or when Sinopé is doing an update in the neviweb code.
I'll check if I can set a global parameter, notification True/false or a per device parameter to stop tthose notification.

**Comment by ColtonYYZ** [comment] 2024-09-29 16:29
Hey @claudegel , this is the same problem I have been experiencing for a few months now. You helped me with it but we didn't really get a conclusive answer as to the cause.  It got better for me, where I would only see the message once in a while, but now I am seeing the message sometimes hourly or more.

**Comment by tessierp** [comment] 2024-09-30 17:07
> Hey @claudegel , this is the same problem I have been experiencing for a few months now. You helped me with it but we didn't really get a conclusive answer as to the cause. It got better for me, where I would only see the message once in a while, but now I am seeing the message sometimes hourly or more.
> 
> ![neviweb](https://private-user-images.githubusercontent.com/33189874/371871895-6aed91bc-6c74-47cd-92b7-52658cf02212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTU5ODUsIm5iZiI6MTcyNzcxNTY4NSwicGF0aCI6Ii8zMzE4OTg3NC8zNzE4NzE4OTUtNmFlZDkxYmMtNmM3NC00N2NkLTkyYjctNTI2NThjZjAyMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE3MDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNjI0ODQwMjE1YjNkM2NmZGUxYTg5YTA4MjRhNDhkZTg2MmU1YTIxYWQ2MGU3MDBhNTc1NWQwZTVmNWQwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ug2EhW2b8Qxt7XYM9LIZIkyo_ZR7g5ZSOPpDF-RSFZ0) ![neviweb](https://private-user-images.githubusercontent.com/33189874/371871980-2e486b21-a8b2-4eb8-b0c3-f284aef63078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MTU5ODUsIm5iZiI6MTcyNzcxNTY4NSwicGF0aCI6Ii8zMzE4OTg3NC8zNzE4NzE5ODAtMmU0ODZiMjEtYThiMi00ZWI4LWIwYzMtZjI4NGFlZjYzMDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE3MDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NTM1MGFkZDhhNGVjZDMyZGE5NTIzMTdiZDU0NWVkZjZiOWI3NDFhYTRmNGIwMzlmZWJkODE0ZGQ1ZjU4MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x3dN6a7tbDqUwMHqNsk67HTwHIx1k4oBM82N6aRrilI)

These messages are a result of the WIFI devices disconnecting or some WIFI issue, this can happen to any device. I have many other WIFI devices that lose the signal from time to time and reconnect. These messages are sent to notify you that there was a disconnection. 

I think @claudegel was going to look into a solution to : 
1) Allow us to disable these notifications (I'm using PI-ALERT anyways to notify me of issues on my network)
2) Perhaps a way to notify only once per hour or a configurable time that a device disconnected.
3) Perhaps a way to disable further messages per device until it is acknowledged.

I think option 1) is the most important at least to me as I do not really need it.

**Comment by ColtonYYZ** [comment] 2024-09-30 18:52
Yes I understand devices disconnect once in a while. Attached is a screen print of the log for my unit that was supplied by Sinope just now. As you can see, it doesn't stay disconnected for long. But the amount of times in a day that we get these notifications is a little frustrating. I'm certainly not blaming anyone. And I truly value the time and knowledge that's gone into this integration! I just think it's good to bring up things like this in case it's a precurser to a bigger problem. Especially when other people also are experiening the same symptoms.

Anyway, just for humour, I have setup a separate 2G network that only it will use, and let's see what happens then.
![image](https://github.com/user-attachments/assets/7f6e88cb-fedb-4c35-b4ff-db2863a33649)

**Comment by claudegel** [comment] 2024-10-01 01:58
I just finish a big file at work so now I should have more time to check how we can solve this issue with Sinopé. The problem is a lot more common with wifi devices. Not sure if Sinopé is polling those devices or just wait for the device to report some data like room temperature change, start heating, heat level change or setpoint change. So I just bought a TH1124WF to test how it work and see if we can talk directly to those devices like the zigbee one in ZHA or Z2M. (long term work)
For now the code work like this. We poll Neviweb every scan_interval time (300 sec). If we detect a connection lost from Sinopé about a device (DVCUNVLB error code), a notification is sent and polling is stoped for 20 minutes. Then a new notification is sent when poling is retarted. For now this is what I'm thinking:
- add a parameter to set a longer delay for the notification.
- add a parameter to choose between notification, logging, both or nothing
- add support to be able to disconnect a device from HA.
I think that it is important to know that Sinopé is loosing connection with one device especially during peek period. But I also think that the problem is more common in summer when the thermostat ar inactive then in winter when there is alway something that change with the thermostats.
On my HA I have only zigbee and I get those notifications about once per month or so. But in my case all the devices drop at the same time. This is how I know that Sinopé is doing an update in Neviweb and I need to check is there are new attributes for devices or other changes.

**Comment by tessierp** [comment] 2024-10-01 15:46
@claudegel Those options would be awesome! Thanks for looking into this, much appreciated.

**Comment by ColtonYYZ** [comment] 2024-10-01 17:07
Hey @claudegel!  I really like the idea of the second option, with simply having it logged but notify the user. 

I know that in our home assistant logs lots of times there's warnings in there for a device, as an example something's being depreciated by a certain date and for the developer to fix or adjust their code accordingly. Those warnings do not come through as an alert or notification to the user but it's in the log at least. 

If something like that could be done instead of notifying the user, I think that would be less work for you, better for the end user, and the information still available when needed. 

I don't know what everybody else would think but I think for myself, I would appreciate that option the most.

**Comment by claudegel** [comment] 2024-10-03 00:08
I already send all those to the log. But I know that most people don't check there log because this file is huge and not user frendly. So I'll implement the above solution and everybody will have the choice of notification or log.

**Comment by claudegel** [comment] 2024-10-03 02:22
I've set a new branch «notification»
https://github.com/claudegel/sinope-130/tree/notification/custom_components/neviweb130
There is a new parameter to add in configuration.yaml, «notify» which can take values : both, nothing, notification or logging.
Default value is nothing, if you omit the notify parameter in configuration.yaml
On my side it load but I'll need to catch some DVCUNVLB error to see if it work. My setting is both.
I've also updated the readme.md of that branch. Let me know if it load and if you catch some error logging

**Comment by tessierp** [comment] 2024-10-03 13:35
@claudegel Thanks for the update, I will give it a try and let you know how it goes.

**Comment by tessierp** [comment] 2024-10-03 13:41
![image](https://github.com/user-attachments/assets/a85f9f1d-2acc-4df2-8d62-75f030781b26)

Hello @claudegel, seems I am having issues. I placed this under neviweb130 where I expected it to be but the parameter is rejected.

**Comment by ColtonYYZ** [comment] 2024-10-03 23:44
Hey @claudegel, thanks as always for your assistance!  Can you let me know what I need to do so I can test this for you? I thought I just needed to download the files you updated yesterday and just re-save them over top of my current files but that messed everything up. I am going to remove the integration and re-add it again, then update the files you advise me to do and/or the steps.  Sorry to bother you with this.

**Comment by claudegel** [comment] 2024-10-04 00:57
Hi you just need to copy all the file from the branch to custom_components/neviweb130 dir to replace the file you have there. Possibly you will need to delete or renam the dir __pycache__ so it will be recreated.
Then in configuration.yaml add this in the section for neviweb130
```
neviweb130:
  username: !secret climate_username
  password: !secret climate_password
  network: !secret climate_gateway130
  scan_interval: 360
  stat_interval: 600
  notify: "both"
```
options are "both", "nothing", "logging" or "notification". Don't forget the brace ""
When it work you'll see in your log the following line:
[custom_components.neviweb130] Setting notification method to: both or wathever option you choose

**Comment by ldupont226** [comment] 2024-10-04 02:57
Hi Claude,
I installed the new Notify integration, I don't know if there is a link. But my Home Assistant has restartded 3 to 4 times in 20 minutes. 
I put the old integration back and now it seems more stable.

**Comment by ColtonYYZ** [comment] 2024-10-04 04:23
So I have tried a few different ways to update my files so I can test for you, but none of the ways I tried worked. I even deleted ALL the files in the folder "neviweb130" and downloaded the updated ones from the URL you gave above but it still kept saying that the integration was not found.

I reverted back to the current release. Restarted HA. Then I downloaded the newly updated files you posted in your URL, overwriting the ones in the neviweb folder. Restarted HA. And I get an error saying: "Configuration warnings
Integration error: neviweb130 - Integration 'neviweb130' not found."

Is it possible for you to push this as a beta release and I could redownload it thru hacs? I'm sorry. I don't know why it's not working for me. I have since rolled back to the current release - not including the updated files you did yesterday.

**Comment by claudegel** [comment] 2024-10-04 13:28
Can you provide more log. Upon HA restart you get a notification that neviweb130 could not be set. If there is a button «view log» could you provide the error message.
Everything load on my side so I need to find out what is your problem

**Comment by claudegel** [comment] 2024-10-05 02:32
I've done few code changes. For those who want to test copy all file in custom_components/neviweb130 and delete the dir __pycache__. It will be recreated by HA upon restart.

**Comment by ColtonYYZ** [comment] 2024-10-05 09:25
@claudegel! Sorry for the delay. I figured out what was happening. I was right clicking on the files and saving as, overwriting the files in the neviweb folder on my side. Doing so, the files that were downloaded were filled in with a bunch of HTML so it couldn't parse the files correctly. I then clicked on each file online, and over to the right, clicked on the download arrow "download raw file" and overwrote my files with the raw files I downloaded. Rebooted, added the notify line in my config, rebooted and voila! I'm back in business with no errors!

**Comment by tessierp** [comment] 2024-10-05 16:35
> I've done few code changes. For those who want to test copy all file in custom_components/neviweb130 and delete the dir **pycache**. It will be recreated by HA upon restart.

@claudegel So I guess there is no way to automate the update when a new version is available? I mean anytime an update is done we have to install the affected files manually? I know there isn't a lot of files but it is often more prone to mistake to do things manually. Writing over the files I have in custom_components/neviweb130 with what is in https://github.com/claudegel/sinope-130/tree/notification/custom_components/neviweb130, could that mess up any setup I've done on my end?

Also, It is strange  a bit because if no update was done automatically, I haven't had any notifications for a while so, I'm wondering if the package was updated by itself??

**Comment by claudegel** [comment] 2024-10-05 17:32
The __pycache__ dir is in cuatom_components/neviweb130. It is regenerated each time a new version is added. Normally it also update on each file change. But some time when you do a manual update is is possible that pycache is not updated. To be sure, erasing __pycache__ force a reset when you restart HA. It is python that recompile the files.
If update is via HACS, __pycache__ is always resetted.

**Comment by claudegel** [comment] 2024-10-05 18:20
For those who succeeded in manual update of neviweb130 file please set notify attributes to value both until you get at least one notification for a device disconnected. If you set it to nothing we'll never know if it work to get the notification.

**Comment by ldupont226** [comment] 2024-10-05 22:21
Hello Claude,
I installed the new version, and configured notify: "both", I closed the breaker on one of my thermostats for over an hour. I haven't received a notification and I don't see a problem in the log. neviweb.com sees it as offline.

**Comment by claudegel** [comment] 2024-10-06 01:29
In your home-assistant.log do you see DVCUNVLB ?
You will receive notification only if Neviweb send this error message

**Comment by claudegel** [comment] 2024-10-06 02:01
@ldupont226 did your thermostat was a wifi or a zigbee one?

**Comment by ldupont226** [comment] 2024-10-06 02:11
Hi Claude,
No I can't find DVCUNVLB in homeassistant.log,
Strangely it is seen as online in home assistant, I can change the temperature without error.

![image](https://github.com/user-attachments/assets/954f1ccc-4c23-498c-b278-1bcaee414e7e)
![image](https://github.com/user-attachments/assets/2c378862-1a71-4d61-94b1-ddccb3d2c9c2)

**Comment by ldupont226** [comment] 2024-10-06 02:17
WIFI

**Comment by claudegel** [comment] 2024-10-06 02:44
If you change the setpoint in HA you can see the same change on the thermostat ?

**Comment by ldupont226** [comment] 2024-10-06 03:01
No because when I click on the thermostat it displays the screenshot of the previous message.
But there is a strange thing, I don't know if it's a clue, at first the logo was grayed out, after changing temperature and mode in Home Assistant it has this look.


![image](https://github.com/user-attachments/assets/27b22ed6-9deb-4e8d-94c9-0ffa56377d81)

**Comment by ldupont226** [comment] 2024-10-06 12:39
After turning the circuit breaker back on, the thermostat settings in home assistant took over the actual thermostat settings.

**Comment by ldupont226** [comment] 2024-10-06 18:02
Forget the mention of the grayed out icon from yesterday's message because on the mobile it's grayed out and the web page is with --, so not a clue

**Comment by claudegel** [comment] 2024-10-07 00:19
We will wait for next error to come from Neviweb before I push that branch into master.
Check your log from time to time to see if DVCUNVLB appear
Look for line [custom_components.neviweb130.climate] Updating neviweb130 climate name of your thermostat which will contain error code DVCUNVLB.
If it is present we'll see if the notification are fired when notify is set to both.

**Comment by ColtonYYZ** [comment] 2024-10-07 15:09
So far in my logs, I am not finding DVCUNVLB anywhere. Then again, I also setup a separate 2.4 GHz access point and since then I haven't received any error either. So not sure if it's the isolated AP or the updates you've made that are solving the issue. But I will keep you posted as soon as I see the error DVCUNVLB.

**Comment by tessierp** [comment] 2024-10-08 18:29
I guess I didn't get the HACS updates including Neviweb130 since I had a bunch of notifications today. @claudegel, is there a way for me to know which version I have right now? Is there a version # somewhere in a file I could look?

**Comment by claudegel** [comment] 2024-10-09 00:36
To view the version number you can check in HACS you can add the info of installed version and available version. In HACS clic on the gear in the upper wright corner to add those property.
Also directly in neviweb130 check in file `__init__.py` for a line version = '2.8.3' near line 115.
Since the nnew version in branch notification, version info have been migrated to schema.py file near line 85

**Comment by tessierp** [comment] 2024-10-09 00:59
@claudegel So yeah I'm 2.8.3. If I add notify, it complains I have an invalid config.

**Comment by claudegel** [comment] 2024-10-09 01:20
You must copy and install the file from branch notification which is at 2.8.4. In your version the notify option is not supported.
https://github.com/claudegel/sinope-130/tree/notification/custom_components/neviweb130
Copy all files there to replace the one you have in custom_components/neviweb130

**Comment by tessierp** [comment] 2024-10-09 16:33
@claudegel I was hoping to get that download automatically from the master branch and no have to git clone and copy all the files. Anyway at the moment I copied manually and it works. I was under the impression that 2.8.3 was the version where you made those fixes. HCAS still reports the latest version to be 2.8.3, however manifest.json in the directory you asked me to copy is 2.8.4, hence for HACS the latest is still 2.8.3.

Anyway, the parameter (notify) seems to work. Thanks.

**Comment by tessierp** [comment] 2024-10-12 02:18
I think this issue is now closed unless someone else still has issues?

**Comment by claudegel** [comment] 2024-10-12 02:34
I'll push a new release this weekend and explain the value for the new notify parameter. Default value will be "both". Those who have wifi devices will be tell to set it to "both" or "logging", or to set it to "nothing" if they don't want to know if a device is disconnected.

**Comment by ldupont226** [comment] 2024-10-12 04:04
With the tests I did last week and yesterday
with notify: "notification" and notify: "both",
by closing the thermostat circuit breaker I never received a message, nor a DVCUNVLB in the log.
The Neviweb.com web application only says it is offline. And nothing tells me in Home Assistant that it is offline.

**Comment by ldupont226** [comment] 2024-10-14 01:26
Bonjour Claude
En logger debug je vois ce message :

2024-10-13 21:21:08.040 DEBUG (SyncWorker_6) [custom_components.neviweb130.climate] Updating neviweb130 climate 
**Garage (0.115 sec): {'error': {'code': 'DVCUNVLB', 'data': {'identifier': '0cb815fffee4d2e0'}}}**
mais pas de message.
configuretion yaml:   notify: "notification"

**Comment by claudegel** [comment] 2024-10-14 02:16
Ok et tu as installer la branche notification, version 2.8.4 ?
je vais vérifier s'il y a pas un petit bug

**Comment by ldupont226** [comment] 2024-10-14 02:31
oui 2.8.4

**Comment by claudegel** [comment] 2024-10-14 02:47
OK j'ai modifié cliamte.py puisque c'est un thermostat. Remplace ton climate.py par celui de la branche notification. Puis redémarre HA. Les prochain DVCUNVLB devraien être notifiés correctement.

**Comment by ldupont226** [comment] 2024-10-14 04:12
Ce soir j'ai testé avec notify: "both"
et pas reçu de message demain je ferai d'autres tests avec notify

**Comment by ldupont226** [comment] 2024-10-15 00:34
Bonsour Claiude, ce soir j'ai fait un autre test avec  notify: "notification"
Hier je n'avais pas ettacé __pycache__ après l'installation du nouveau fichier cliamte.py, ce, que j'ai fait ce soir.
j'ai aussi redémarré Home Assistant.
J'ai fermé le breaker du thermostat.
Après 30 minutes je n'ai pas reçu de notification.

scan_interval: 300
stat_interval: 900

**Comment by claudegel** [comment] 2024-10-15 02:24
Pour ton scan_interval ne descends pas en bas de 300 ou Sinopé va te débrancher.
Le problème avec DVCUNVLB c'est qu'il faut attendre ces messages d'erreur lors des mises a jour de nos appareils sur Neviweb. De mon coté j'en ai pas recu. Habituellement j'en recois un paquet quand Sinopé fait des mise a jour de Neviweb. Avec la saison des crédit qui arrive ils vont certainement en  faire . J,ai hâte de pouvoir valider que tout marche bien pour pouvoir activer cette version de neviweb130.

**Comment by ldupont226** [comment] 2024-10-15 03:05
Le breaker termostat a été fermé pendant 12 heures.
Comme je te l'ai écris dans le message hier je vois le **DVCUNVLB** pour mon thermostat dans les log quand je suis en debug (custom_components.neviweb130: debug).
Mais je ne recois pas de notification.

**Comment by claudegel** [comment] 2024-10-15 12:47
Pouvez-vous valider dans vos log pour la ligne contenant ceci:
[custom_components.neviweb130] Setting notification method to:
est-ce notification ?

**Comment by ldupont226** [comment] 2024-10-15 13:13
oui
2024-10-15 09:10:23.230 DEBUG (SyncWorker_8) [custom_components.neviweb130] Setting notification method to: notification

**Comment by claudegel** [comment] 2024-10-16 02:03
Ce soir je viens d'avoir des notifications pour tous mes appareils sur mon GT130. J'ai reçu un DVCUNVLB pour chacun de mes appareils. Notify est a «both» et ça a fonctionné parfaitement.
Après 20 minutes ça a recommencé avec les updates. Ça a touché mes thermostats, sensor et switch.

**Comment by claudegel** [comment] 2024-10-16 02:22
Je pense dans mon cas, le problème venait de Videotron. J'ai des timeout sur internet. mais quand même Neviweb a envoyé DVCUNVLB pour chacun des appareils et la notification s'est fait correctement.
J'ai ajouter du débug dans climate.py pour voir si lors de la réception du DVCUNVLB, le code passe bien par l'envoi des notifications de ton coté.

**Comment by ldupont226** [comment] 2024-10-16 02:57
Voici le log 

[netweviewClimate.log](https://github.com/user-attachments/files/17388603/netweviewClimate.log)

**Comment by claudegel** [comment] 2024-10-18 02:25
dans votre log il y a la ligne suivante:
[custom_components.neviweb130.climate] NOTIFY value: nothing, (SKU: TH1124WF)
Ce warning est envoyé dans la partie du code qui envoi les log et les notification pour le message d'erreur DVCUNVLB.
Par contre je vois au début de vos log 
Setting notification method to: notification
Je vais vérifier si il y a quelques chose qui affecte la valeur de Notify

**Comment by claudegel** [comment] 2024-10-18 02:47
je pense que j'ai trouvé.
Pouvez-vous valider la ligne 90 de schema.py
ça devrait être NOTIFY = "both" mais je pense que avant j'avais mis NOTIFY = "none"
la valeur du parametre notify semble être remplacée par cette ligne.
Je vais tester de mon coté pour valider et trouver une correction.

**Comment by ldupont226** [comment] 2024-10-18 11:44
Bonjour Claude en effet après avoir fait la correction dans le fichier schema.py
j'ai recu la notification , et aussi visiblle dans log.
Je remarque que la section dans laquelle j'ai fait la correction sont les valeur par défauts.
Donc on dirait qu'il ne tien pas compte de ce qui est dans configuration.yaml.

Est ce que le parametre est case sensitive , 
je ramaque que dans schema.py c'est NOTIFY = "both" et dans configuration.yaml c'est notify: "both"

**Comment by claudegel** [comment] 2024-10-18 17:44
Non le parametre doit être notify. Je suis a tester une patch pour corriger. Effectivement la valeur par défaut écrase le paramètre choisit. je vais faire la mise a jour sur la branche notification aujourd'hui.

**Comment by claudegel** [comment] 2024-10-18 17:53
Je confirme que ma patch fonctionne ici. Je reboot une dernière fois en changeant mes parametres et je vais pousser la patch.

**Comment by claudegel** [comment] 2024-10-18 18:38
J'ai patché la branche notification. Ça devrait fonctionner maintenant. Si ca va de votre coté je vais pouvoir faire un release.

**Comment by ldupont226** [comment] 2024-10-18 21:03
J'ai testé "logging" et "notification".
Et tout fonctionne comme prévu.
Fonctionne très bien
Merci Claude

**Comment by ldupont226** [comment] 2024-10-19 22:08
est ce que ça vaut la peine que je test les 2 autres. On sait par défaut que nothing fonctionne

**Comment by claudegel** [comment] 2024-10-19 23:41
Non maintenant qu'on a trouvé le bug les quatres options fonctionnent.
Je dois juste trouver un bug avec un thermostat TH1124ZB qui produit une erreur pour un attribut qui n'est plus utilisé et je publie une nouvelle version.

Merci pour ton aide.

**Comment by claudegel** [comment] 2024-10-21 00:51
La version 2.8.4 a été publiée.

**Closed by claudegel** 2024-10-21 00:51 UTC
